
package Formulario;

import java.util.Locale;

/**
 *
 * @author PC-DESKTOP
 */
public class ConvertidorMoneda extends javax.swing.JFrame {
    /**
     * Creates new form ConvertidorMoneda
     */
    public ConvertidorMoneda() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonConvertir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonNuevo = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        txtconvertir = new javax.swing.JTextField();
        cbtipoMoneda = new javax.swing.JComboBox();
        txtresultado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcambio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonConvertir.setText("Convertir");
        botonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConvertirActionPerformed(evt);
            }
        });
        getContentPane().add(botonConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, 30));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione Tipo de Moneda:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 22));

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Digite la Cantidad a Convertir:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, 23));

        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(botonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 77, -1));

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 77, -1));
        getContentPane().add(txtconvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 130, -1));

        cbtipoMoneda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Peso Mexicano", "Dolar Americano", "Euro", "Dolar Australiano", "Quetzal" }));
        getContentPane().add(cbtipoMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 130, -1));

        txtresultado.setEnabled(false);
        getContentPane().add(txtresultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 130, -1));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tasa de Cambio:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 100, -1));

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Convertido Lps :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        txtcambio.setEnabled(false);
        getContentPane().add(txtcambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Abstractos_Fondo-de-pantalla-Abstracto-162.jpg"))); // NOI18N
        jLabel3.setText("xzcxczxcz");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 330));

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConvertirActionPerformed
        
        double montoDivisa;
        double resultadoConversion = 0;
       
        montoDivisa = Double.parseDouble(txtconvertir.getText());
        
        
        int seleccion = cbtipoMoneda.getSelectedIndex();
        
        if(seleccion == 0 ){
        
            resultadoConversion = montoDivisa * 1.28;
            txtcambio.setText("1.28");
            
        } else if(seleccion == 1){
            resultadoConversion = montoDivisa * 24.40;
            txtcambio.setText("24.40");
            
        } else if(seleccion == 2){
            resultadoConversion = montoDivisa * 27.62;
            txtcambio.setText("27.62");
            
        } else if(seleccion == 3){
            resultadoConversion = montoDivisa * 17.29;
            txtcambio.setText("17.29");
            
        } else if(seleccion == 4){
            resultadoConversion = montoDivisa * 3.18;
            txtcambio.setText("3.18");
        }
        
        txtresultado.setText(String.valueOf(resultadoConversion));
        
    }//GEN-LAST:event_botonConvertirActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
       
        this.txtconvertir.setText(null);
        this.txtresultado.setText(null);
        this.txtcambio.setText(null);
        
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertidorMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertidorMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertidorMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertidorMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertidorMoneda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConvertir;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox cbtipoMoneda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtcambio;
    private javax.swing.JTextField txtconvertir;
    private javax.swing.JTextField txtresultado;
    // End of variables declaration//GEN-END:variables
}
